version: '3.8'
services:
  app:
    build:
      context: .
      args:
        - GO_VERSION=1.19
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: "redis:alpine"
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    env_file:
      - .env
    volumes:
      - redis-data:/data

volumes:
  redis-data:

